### ISSUE TITLE
dzil test fails on clone

### ISSUE THREAD

**Issue by szabgab** [ology/MIDI-Drummer-Tiny#1]
Hi,

I tried to run the tests on a clone of the repository but I got this. I could add my own PAUSE credentials to that file, but I I am not sure if that would be the right thing and wonder why is it even needed just to run the tests?

Am I doing something incorrectly?

```
$ dzil test
[DZ] building distribution under .build/zN7XR1Tvl8 for installation
[DZ] beginning to build MIDI-Drummer-Tiny
[DZ] guessing dist's main_module is lib/MIDI/Drummer/Tiny.pm
[VersionFromModule] dist version 0.0904 (from lib/MIDI/Drummer/Tiny.pm)
[Authority] PAUSE credentials not found in "config.ini" or "dist.ini" or "~/.pause"! Please set it or specify an authority for this plugin.
[Authority] PAUSE credentials not found in "config.ini" or "dist.ini" or "~/.pause"! Please set it or specify an authority for this plugin. at inline delegation in Dist::Zilla::Plugin::Authority for logger->log_fatal (attribute declared in /home/gabor/perl5/lib/perl5/Dist/Zilla/Role/Plugin.pm at line 59) line 18.
```

**Comment by ology** [comment]
Indeed - why are the PAUSE credentials involved?  I am stumped so far. 😕

**Comment by ology** [comment]
@szabgab - The Authority plugin is getting confused for some reason.  I will take the advice of a person on the irc.perl.org #distzilla IRC channel and explicitly set authority.  Please pull and retest!

**Comment by szabgab** [comment]
It works now, thanks. I'll try to send a PR for the use of Travis-CI soon.
